Wildcards
code-kiwi/42_MINISHELL pull request #13
Opened 2024-04-17 12:31 UTC by BenjaminRap

Ajout du pathname expansion.
Il s'effectue de différentes manières en fonction du contexte : 
-pour un token normal, il y a le quote removal, le variable expansion et le pathanme expansion.
-pour un assignement word dans un export : il y a la quote removal et le variable expansion lorsqu'on l'exporte, quand on l'utilise, il n'y a que le pathname expansion
-pour une redirection (hors here_doc) il y a les trois mais il faut tester que la liste renvoyée par expand strings ait une length de 1
-pour un here_doc il n'y a que le quote_removal.
Pour cela, je n'ai qu'une fonction : expand_string, il faut lui donner en paramètres un char options qui peut avoir plusieurs valeurs : 
-O_QUOTE qui permet d'enlever les quotes
-O_PATH qui permet d'utiliser les wildcards
-O_VAR qui permet d'utiliser les variables
On peut en faire des combinaisons : O_PATH | O_QUOTE ...

La fonction expand_string prend en paramères ce char options, le shell et un pointeur sur la string que l'on veut étendre.
La fonction renvoie une liste de string qui correspondent à toutes les solutions.
La string envoyée en paramètres seras modifiée mais ne seras pas free, il faut donc la free après.
Bien prendre en compte que la string rentrée en paramètres seras modifiée, elle correspondras à la string avant le pathname expansion, c'est à dire sans les quotes avec la valeur des variables remplacées.
J'ai fait ça parce que ça m'arrangais mais je peux le changer.

Le résultat de expand_string est trié par ordre alphabétique, cela permet d'avoir le même résultat que bash pour pouvoir automatisé les tests.

La plupart des changements de cette pull request sont dues aux headers, les fonctions importantes sont : expand_string et lst_sort.

2024-04-21 20:42 UTC, code-kiwi requested changes
Ouah, gros travail de logique et bravo pour ton nettoyage, c'est beaucoup plus propre et plus simple depuis que tu es repassé sur ta première PR.
Là, le code est plus lisible et compréhensible, et le fait qu'il n'y ait pas de répétition comme celle qu'il y avait entre `remove_quote()` et ta fonction `search_wildcard()` est bon signe. On m'a toujours dit que, quand on faisait deux fois la même chose c'est qu'on avait mal architecturé un élément.

Il n'y a qu'un élément qui me semble clocher: tu ne fermes pas le répertoire ouvert lorsque ton premier `readdir()` échoue, le reste semble nickel, même si je ne maîtrise pas assez le sujet pour trouver des failles auxquelles tu n'aurais pas pensé.
Bien joué 🙂

2024-04-21 20:42 UTC, code-kiwi commented on srcs/expansion/expand_wildcard.c
> +	if (file == NULL)
Tu ne sembles pas appeler `closedir(current_directory);` dans ce cas d'erreur.
On peut peut-être éviter ce premier appel à `readdir()` pour appeler la fonction au début de la boucle while? Je vois que sinon, c'est un peu court en nombre de lignes 😕

2024-04-21 20:42 UTC, code-kiwi commented on srcs/expansion/string_equal_wildcard.c
> +		return (str_wildcard == str_b);
Je ne vois pas comment ça pourrait arriver et renvoyer `true`, mais c'est peut-être juste un contrôle d'arguments.

2024-04-24 07:37 UTC, BenjaminRap commented on srcs/expansion/string_equal_wildcard.c
> +		return (str_wildcard == str_b);
Si un des deux est NULL, il renvoie false, mais si les deux sont NULL, il renvoie true, car NULL == NULL

2024-04-24 07:38 UTC, BenjaminRap commented on srcs/expansion/expand_wildcard.c
> +	if (file == NULL)
Bien vue, c'est une bonne idée

2024-04-24 07:51 UTC, BenjaminRap commented on srcs/expansion/expand_wildcard.c
> +	if (file == NULL)
Au final, j'ai juste enlevé le premier test pour savoir si file est NULL.
Comme ça, si il est NULL, il rentre pas dans le while et on ferme le directory.
D'ailleurs, pour savoir si la fonction expand_string ou expand_wildcard n'a pas marché, il faut checker errno.

2024-04-24 07:54 UTC, BenjaminRap commented
A retenir de cette PR, c'est que pour vérifier si les fonctions expand_wildcards et expand_strings n'ont pas marché, il faut checker errno.
Si errno = 0 et que leur résultat est NULL, c'est que O_PATH était inclus dans options et qu'il n'y a aucun fichier qui correspond à la wildcard.

2024-04-24 08:00 UTC, merged