Environment
code-kiwi/42_MINISHELL pull request #9
Opened 2024-04-03 12:59 UTC by code-kiwi

2024-04-03 14:50 UTC, BenjaminRap commented on srcs/env/env_utils.c
1-Dans ta fonction env_extract, tu split ta ligne avec '=', or tu puex avoir plusieurs egals dans une assignation, dans ce cas la, le premier egal est le egal d assignation et les autres font parti de valeur.
ex : TEST=truc=muche
$TEST
-> truc=muche

2024-04-03 14:53 UTC, BenjaminRap commented on srcs/env/env_utils.c
2-Es tu sur de vouloir ft_strdup dans la fonction env_get ?
Si c'est pour qu on ne puisse pas changer la valeur, tu pourrais renvoyer un const (je crois).

2024-04-03 14:56 UTC, BenjaminRap commented on srcs/env/env_utils.c
meme si on fait : 
export "TEST=truc"=muche
cela nous donneras :
echo $TEST
->
truc=muche
J'ai regarde ca que vite fait mais je pense que si tu divise ta string en deux : avant et apres le premier '=' ca devrais marcher

2024-04-03 14:59 UTC, BenjaminRap requested changes
Je crois qu il y a une erreur dans env_extract, decris dans les coms.
Le ft_strdup dans env_get est a discuter.
Sinon tout est parfait :+1:

2024-04-04 09:04 UTC, code-kiwi commented on srcs/utils/ft_split_key_val.c
> +
Fichier ajouté pour faire un split convenable.

2024-04-04 09:04 UTC, code-kiwi commented on srcs/env/env_utils.c
> +		split = ft_split_key_val(*envp, ENV_KEY_VALUE_SEPERATOR);
Appel au nouveau split

2024-04-05 07:06 UTC, merged